### ISSUE TITLE
Can the new "social sharing image" feature be shown on the homepage feed? 

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-5.0-Bugs#12]
I would like the social sharing image to be able to be shown on the home feed because it's a thumbnail and will look much better IMO.

**Comment by jetlej** [comment]
If it's on the homepage, then wouldn't you just want it on the actual article page too?

**Comment by JonBrooksX** [comment]
See the comparison between the social and standard featured image. I thought the only place where you shouldn't see the text overlay is when the HE default text overlay is there. In full screen blog post view. 

Is it possible to have social image replace featured image everywhere apart from where the white text is overlaid? 

![mystical science](https://cloud.githubusercontent.com/assets/13107838/8545303/05b8541a-24a5-11e5-8bf5-a0762d1e5416.jpg)
![beyond science](https://cloud.githubusercontent.com/assets/13107838/8545092/06212f1e-24a3-11e5-86b5-831236b4d5cd.jpg)

**Comment by MSchirp** [comment]
I like this.

**Comment by jetlej** [comment]
@JonBrooksX - That image is DOPE. So sick! Alright your wish is my command :)

**Comment by jetlej** [comment]
Done
