### ISSUE TITLE
Bug when linking feed articles on buffer

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-5.0-Bugs#13]
This is the exact link: 

http://www.highexistence.com/links/view/the-science-behind-munchies-marijuana-and-your-appetite/?utm_content=buffer19861&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer

**Comment by MSchirp** [comment]
This happens every time you browse to a submitted link and it shows in the 'old view', with the navigation bar on the left. See:

![screen shot 2015-07-05 at 17 49 44](https://cloud.githubusercontent.com/assets/13124056/8512344/3ac131d0-233e-11e5-8443-da894cf1bfd3.png)
![screen shot 2015-07-05 at 17 49 19](https://cloud.githubusercontent.com/assets/13124056/8512345/3adcb202-233e-11e5-89bc-e2498d3b4167.png)
![screen shot 2015-07-05 at 17 48 18](https://cloud.githubusercontent.com/assets/13124056/8512346/3add13a0-233e-11e5-8cde-d2b84987a2d5.png)

**Comment by jetlej** [comment]
What does this have to do with buffer? I see the same thing if I load the page without their URL parameters. 

http://www.highexistence.com/links/view/the-science-behind-munchies-marijuana-and-your-appetite/

Reminder that some links can't use iframes, so they use the non-iframe view

**Comment by MSchirp** [comment]
So only the non-iframe links show the navigation bar on the left? 

Could you limit the total characters then for the non-iframe articles? Huge swaps of texts, as seen in the screenshots I made, makes HE appear to be broken.

**Comment by jetlej** [comment]
@MSchirp - We do want it to show the whole article, no? I'm not sure why that article is just one big block of text. Usually it's formatted just fine.

**Comment by jetlej** [comment]
@MSchirp - Comment above

**Comment by MSchirp** [comment]
Could you answer my first question?

And yeah - if the format is good, then it should show the whole text imo.

**Comment by jetlej** [comment]
Yes only the non-iframe links show the sidebar. iFrames need the whole page width or else they will be unusable. 

I can't programmatically tell if the format is good, so it must just always show full text.
