### ISSUE TITLE
Related Posts Shortcode Not Working

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-5.0-Bugs#21]
I can't get the related posts shortcode to work. 

[related url="http://highexistence.com/50-life-secrets" title="50 Life Secrets & Tips”]

I've inserted that and other variations of it into articles but nothing worked.

**Comment by jetlej** [comment]
Totally stumped on this one. I copy/pasted the code from Wordpress.org, so just posted a question on StackoverFlow. 

It was working before!

**Comment by jetlej** [comment]
Figured it out! You had a curly quote at the end of your shortcode. See how it's more curly than the other quotes? 

" VS ”
