### ISSUE TITLE
Add a Question of the Day Category to Discussions Submission

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-5.0-Bugs#22]
This is small but I'd like these questions of the day to have their own category. Is there also any way for the Martijn's daily discussions and my question of the day to look as if it's coming from HE not one of us?

**Comment by jetlej** [comment]
@JonBrooksX 

1) I just added a categories box for when you create a forum category. Add the category 'Admin Posting Only' and have it checked when you publish the category. Must be spelled exactly like that. That will allow only admins to select that category when creating a post. 

2) Create a HighExistence user and quick-switch to them when posting

**Comment by MSchirp** [comment]
Preferably we need to a bot to post these automatically, with a fixed text, and a link back to the previous edition.
