### ISSUE TITLE
Shitty fonts on some of the older blog posts.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-5.0-Bugs#29]
For some reason the correct fonts are not appearing on some older posts. See here:

http://www.highexistence.com/lifestyle-design-start-living-your-life-now/

**Comment by MSchirp** [comment]
Did you miss Jordan's reply to you on Slack regarding this issue? This is why I think issues should be contained to Github only, to minimize cross-communication. 

"jordan [1:39 AM] 
yeah bc they have inline CSS in them

jordan [1:39 AM]
which is overriding the theme CSS

jordan [1:39 AM]
if you see that, please go in and delete the inline CSS"
