### ISSUE TITLE
Blog Post Feed Frozen

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-5.0-Bugs#3]
I've noticed that the blog feed isn't showing the new posts. There should be two new posts showing up, that aren't. 

They're showing up on the feed, but not the "blog" feed. 

http://www.highexistence.com/blog/

**Comment by jetlej** [comment]
Woo! That was a nasty bug! I'm glad you caught that. There were implications far beyond just the blog page that could have been slowing down the site.
