### ISSUE TITLE
Sharing articles through mail doesn't work.

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-5.0-Bugs#30]
See screenshot of mail I received:

![screen shot 2015-07-14 at 15 40 36](https://cloud.githubusercontent.com/assets/13124056/8674585/22dcbff0-2a3f-11e5-90f3-f95087547835.png)

**Comment by jetlej** [comment]
I have no idea what he's talking about. We don't have a 'send through email' button.

**Comment by MSchirp** [comment]
haha - that is actually funny. I send him an e-mail for clarification.

**Comment by MSchirp** [comment]
This is what he said:

I am accessing your site from an iPad (if that is relevant). In the lower left corner of every page is an upper arrow sharing icon. Clicking on it reveals sharing choices: copy link, Facebook, Twitter, text, email

Sent from my iPad

**Comment by jetlej** [comment]
He's referring to an built-in iOS function. This has nothing to do with our website.
