### ISSUE TITLE
Discussion: Comment = Upvote Not Working

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-5.0-Bugs#31]
![screenshot 2015-07-14 17 19 47](https://cloud.githubusercontent.com/assets/13107838/8678456/9ede163c-2a4c-11e5-8ab1-39e627fe9bfc.png)

Noticed there are more comments than upvotes on this discussion.

**Comment by jetlej** [comment]
Seems to have evened itself out since then. 11 comments and 17 upvotes?
