### ISSUE TITLE
HE site jitters when notification bar is open.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-5.0-Bugs#36]
I'm on a PC in Google Chrome. When I have my notifications over and move my mouse back and forth across the screen, the screen jitters/wiggles back and forth.

**Comment by JonBrooksX** [comment]
Yeah I brought this up before I think. Check if the scroll bar on the left disappears.

**Comment by lostboyevsky** [comment]
Ah, yeah it does.

**Comment by lostboyevsky** [comment]
This issue actually seems to happen with any drop-down menu on the site, not just the nav bar.

**Comment by jetlej** [comment]
Fixed. The point of this is to not allow the rest of the site to scroll as you scroll through a menu or a sidebar, but the workaround to NOT have the scroll bar disappear and jitter was not complicated. So I just removed that functionality
