### ISSUE TITLE
Mouse scrolling issue.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-5.0-Bugs#39]
Usually I don't use an actual mouse, but I do at work, and my mouse has one of those scroll buttons on it (I think most mice do nowawdays). You know how you can click the scroll button then drag down in order to scroll down a page with such a mouse? Yeah, well, when I do that on HE and try to go down really fast, sometimes the mouse icon on the screen gets frozen as the downward scroll icon and I can no longer click on anything and have to refresh the page.

**Comment by jetlej** [comment]
I don't have access to a PC and wouldn't know how to fix this anyways + seems minor, so tagging as wontfix
