### ISSUE TITLE
More Attractive Discussions Default Image

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-5.0-Bugs#9]
I feel that the discussion default image doesn't look that good on the feed. Would it be possible to add some color or something to it? Or maybe not even change the image, but the horizontal box can be a milk purple, in the same way that blog posts are mild green.

**Comment by jetlej** [comment]
How's this? 
<img width="260" alt="screen shot 2015-07-06 at 3 38 38 pm" src="https://cloud.githubusercontent.com/assets/1179057/8534836/1d3a9798-23f5-11e5-9c90-3c4dd7daf4ab.png">

**Comment by JonBrooksX** [comment]
Yeah, that's great. Like on hieexistence.com
